[build-system]
requires = ["setuptools>=75.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pycanari"
version = "0.2.5"
description = "Canari is an open-source library for online change point detection in univariate time series."
license = { text = "MIT" }
requires-python = ">=3.10, <3.13"

authors = [
  { name = "Van-Dai Vuong, Luong-Ha Nguyen, and James-A. Goulet", email = "james.goulet@polymtl.ca" }
]

classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

dependencies = [
  "matplotlib==3.11.1",
  "numpy==2.5.1",
  "pandas==3.0.5",
  "tqdm==4.70.0",
  "fire==0.7.1",
  "statsmodels==0.14.6",
  "optuna==4.9.0",
  "pytest==9.1.1",
  "ray[tune]==2.56.1",
  "pyTAGI==0.2.1",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://bayes-works.github.io/canari/index.html"
Repository = "https://github.com/Bayes-Works/canari"


