name: Build & Deploy Docs

on:
  push:
    branches:
      - main    
  workflow_dispatch:

jobs:
  docs:
    name: Generate and Deploy Sphinx Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build HTML with Sphinx
        working-directory: docs
        run: |
          sphinx-build -b html . _build/html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
